name: glo_insta_bug_reporter
description: A package provides an easy way to instantly capture screenshot, edit it, describe and create card on glo board instantly in Flutter project.
version: 0.1.0
author: Bohdan Nikoletti <geekowldevelopers@gmail.com>
homepage: https://github.com/BohdanNikoletti/GloInstaBugReporter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  oauth2: ^1.2.3
  sensors: ^0.4.0+1
  flutter_webview_plugin: ^0.3.4
  shared_preferences: ^0.5.2
  json_serializable: ^2.2.2
  json_annotation: ^2.2.0
  build_runner: ^1.4.0
  http: ^0.12.0+2
  http_parser: ^3.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true